# Generated by Django 5.0.4 on 2024-05-15 01:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('dueDate', models.DateTimeField()),
                ('description', models.TextField(blank=True, default=None)),
                ('status', models.IntegerField(choices=[(1, 'Todo'), (2, 'Missing'), (3, 'Done')], default=1)),
                ('file', models.FileField(upload_to='')),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='SK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=36)),
                ('name', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('logo', models.ImageField(blank=True, default='./static/Logo.png', upload_to='uploads/')),
                ('badge', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Compliant Badge'), (2, 'Early Badge'), (3, 'Transparent Badge'), (4, 'Impact Badge')]), size=None)),
                ('xp', models.IntegerField(default=0)),
            ],
        ),
    ]
