# Generated by Django 5.0.4 on 2024-05-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='sk',
            name='logo',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
