# Generated by Django 5.0.4 on 2024-05-15 03:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_requirement_file_alter_sk_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
